"""update RecipeIngredient

Revision ID: 020acaad072f
Revises: ccb683d7069e
Create Date: 2024-05-31 11:29:55.503080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '020acaad072f'
down_revision = 'ccb683d7069e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe_ingredients', schema=None) as batch_op:
        batch_op.alter_column('plant_family_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe_ingredients', schema=None) as batch_op:
        batch_op.alter_column('plant_family_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
