"""update step type and step

Revision ID: 0b89e97c0201
Revises: f29fe8019ee7
Create Date: 2024-02-09 10:03:56.101987

"""
from alembic import op
import sqlalchemy as sa
from app.models import generate_uuid


# revision identifiers, used by Alembic.
revision = '0b89e97c0201'
down_revision = 'f29fe8019ee7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planting_step_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('svg_icon', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('color', sa.String(length=16), nullable=True))

    op.execute("UPDATE planting_step_types SET svg_icon = '' WHERE svg_icon = NULL")
    op.execute("UPDATE planting_step_types SET color = '' WHERE color = NULL")

    with op.batch_alter_table('planting_step_types', schema=None) as batch_op:
        batch_op.alter_column('svg_icon', existing_type=sa.Text(), nullable=False)
        batch_op.alter_column('color', existing_type=sa.String(length=16), nullable=False)

    with op.batch_alter_table('planting_steps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_planting_steps_uuid'), ['uuid'], unique=False)

    op.execute(f"UPDATE planting_steps SET uuid = '{generate_uuid()}' WHERE uuid = NULL")

    with op.batch_alter_table('planting_steps', schema=None) as batch_op:
        batch_op.alter_column('uuid', existing_type=sa.String(length=36), nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planting_steps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_planting_steps_uuid'))
        batch_op.drop_column('uuid')

    with op.batch_alter_table('planting_step_types', schema=None) as batch_op:
        batch_op.drop_column('color')
        batch_op.drop_column('svg_icon')

    # ### end Alembic commands ###
