"""updated step_type

Revision ID: 645be69447c3
Revises: f29fe8019ee7
Create Date: 2024-02-08 11:22:36.790321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '645be69447c3'
down_revision = 'f29fe8019ee7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planting_step_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('svg_icon', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('color', sa.String(length=16), nullable=True))

    op.execute("UPDATE planting_step_types SET svg_icon = '' WHERE svg_icon IS NULL")
    op.execute("UPDATE planting_step_types SET color = '' WHERE color IS NULL")

    with op.batch_alter_table('planting_step_types', schema=None) as batch_op:
        batch_op.alter_column('svg_icon', existing_type=sa.Text(), nullable=False)
        batch_op.alter_column('color', existing_type=sa.String(length=16), nullable=False)


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planting_step_types', schema=None) as batch_op:
        batch_op.drop_column('color')
        batch_op.drop_column('svg_icon')

    # ### end Alembic commands ###
