"""empty message

Revision ID: 66156b1cdb83
Revises: 020acaad072f
Create Date: 2024-08-06 14:53:36.291790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66156b1cdb83'
down_revision = '020acaad072f'
branch_labels = None
depends_on = None


def upgrade():
 # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.String(length=5), nullable=False, server_default='ua'))

    # Remove the server_default after the column has been added
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('language', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('language')

    # ### end Alembic commands ###
