"""add ingredients models

Revision ID: 6decc9409f26
Revises: f9f39bac0c53
Create Date: 2024-04-02 10:57:52.481307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6decc9409f26'
down_revision = 'f9f39bac0c53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('additional_ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_additional_ingredients')),
    sa.UniqueConstraint('name', name=op.f('uq_additional_ingredients_name'))
    )
    with op.batch_alter_table('additional_ingredients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_additional_ingredients_uuid'), ['uuid'], unique=False)

    op.create_table('recipe_additional_ingredients',
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('additional_ingredient_id', sa.Integer(), nullable=False),
    sa.Column('text_quantity', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['additional_ingredient_id'], ['additional_ingredients.id'], name=op.f('fk_recipe_additional_ingredients_additional_ingredient_id_additional_ingredients')),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], name=op.f('fk_recipe_additional_ingredients_recipe_id_recipes')),
    sa.PrimaryKeyConstraint('recipe_id', 'additional_ingredient_id', name=op.f('pk_recipe_additional_ingredients'))
    )
    with op.batch_alter_table('recipe_additional_ingredients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recipe_additional_ingredients_uuid'), ['uuid'], unique=False)

    op.create_table('recipe_ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('plant_familie_id', sa.Integer(), nullable=True),
    sa.Column('plant_varietie_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('quantity_type', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['plant_familie_id'], ['plant_families.id'], name=op.f('fk_recipe_ingredients_plant_familie_id_plant_families')),
    sa.ForeignKeyConstraint(['plant_varietie_id'], ['plant_varieties.id'], name=op.f('fk_recipe_ingredients_plant_varietie_id_plant_varieties')),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], name=op.f('fk_recipe_ingredients_recipe_id_recipes')),
    sa.PrimaryKeyConstraint('id', 'recipe_id', name=op.f('pk_recipe_ingredients'))
    )
    op.drop_table('plant_variety_recipe')
    op.drop_table('plant_family_recipes')
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_column('additional_ingredients')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('additional_ingredients', sa.VARCHAR(length=1024), nullable=False))

    op.create_table('plant_family_recipes',
    sa.Column('recipe_id', sa.INTEGER(), nullable=False),
    sa.Column('plant_family_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['plant_family_id'], ['plant_families.id'], name='fk_plant_family_recipes_plant_family_id_plant_families'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], name='fk_plant_family_recipes_recipe_id_recipes'),
    sa.PrimaryKeyConstraint('recipe_id', 'plant_family_id', name='pk_plant_family_recipes')
    )
    op.create_table('plant_variety_recipe',
    sa.Column('recipe_id', sa.INTEGER(), nullable=False),
    sa.Column('plant_variety_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['plant_variety_id'], ['plant_varieties.id'], name='fk_plant_variety_recipe_plant_variety_id_plant_varieties'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], name='fk_plant_variety_recipe_recipe_id_recipes'),
    sa.PrimaryKeyConstraint('recipe_id', 'plant_variety_id', name='pk_plant_variety_recipe')
    )
    op.drop_table('recipe_ingredients')
    with op.batch_alter_table('recipe_additional_ingredients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recipe_additional_ingredients_uuid'))

    op.drop_table('recipe_additional_ingredients')
    with op.batch_alter_table('additional_ingredients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_additional_ingredients_uuid'))

    op.drop_table('additional_ingredients')
    # ### end Alembic commands ###
