"""added svg_icon to step type

Revision ID: 80c1bca6e556
Revises: f29fe8019ee7
Create Date: 2024-02-07 15:25:36.126733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80c1bca6e556'
down_revision = 'f29fe8019ee7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planting_step_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('svg_icon', sa.Text(), nullable=True))
    op.execute("UPDATE planting_step_types SET svg_icon = '' WHERE svg_icon IS NULL")
    with op.batch_alter_table('planting_step_types', schema=None) as batch_op:
        batch_op.alter_column('svg_icon', existing_type=sa.Text(), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planting_step_types', schema=None) as batch_op:
        batch_op.drop_column('svg_icon')

    # ### end Alembic commands ###
