"""fix user language by setter

Revision ID: c9d8f4fbe348
Revises: ea068526cb9e
Create Date: 2024-08-16 14:06:04.389542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9d8f4fbe348'
down_revision = 'ea068526cb9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_language', sa.String(length=5), server_default='ua', nullable=False))
        batch_op.drop_column('language')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.VARCHAR(length=5), server_default=sa.text("'ua'"), nullable=False))
        batch_op.drop_column('_language')

    # ### end Alembic commands ###
