"""updated str to text

Revision ID: d51101854749
Revises: 1750297d3962
Create Date: 2024-02-22 14:41:39.011675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd51101854749'
down_revision = '1750297d3962'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plant_varieties', schema=None) as batch_op:
        batch_op.alter_column('ground_type',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plant_varieties', schema=None) as batch_op:
        batch_op.alter_column('ground_type',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=256),
               existing_nullable=False)

    # ### end Alembic commands ###
