"""add user prefeted language

Revision ID: ea068526cb9e
Revises: 020acaad072f
Create Date: 2024-08-15 10:55:42.790114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea068526cb9e'
down_revision = '020acaad072f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.String(length=5), server_default='ua', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('language')

    # ### end Alembic commands ###
